# Generated by Django 5.0 on 2023-12-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salespersons', '0002_salesperson_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='pic',
            field=models.ImageField(default='', upload_to='salespersons'),
        ),
    ]
